### ISSUE TITLE
random-event-logger - Logs last 24h rather than today's events (suggestion)

### ISSUE THREAD

**Issue by nonhic** [systematic-meerca/neopets-display-scripts#2]
Hello!  I love the scripts here and have a suggestion for the random-event-logger script's display of the events that occurred today.  As it is now, the script pulls the number of events that occurred in the last 24h rather than truly pulling just today's events as it purports to display:
https://github.com/systematic-meerca/neopets-display-scripts/blob/135c4fb16995840a779f9f04e576f194d5223687/random-event-logger.user.js#L251-L252

I am only a novice at this, but I believe this line replacement would better encompass those events that occurred today--on today's date:
`<div> ${events.filter(e => e.timestamp > new Date().setHours(0,0,0,0)).length} </div>`

The difference is negligible, but I play neopets in small amounts across the day, so having it display just today's events is a better comparison day by day for my play-style.  If someone else/the author has a better method of achieving the same result, I would be grateful for it!  Thank you for the scripts!

**Comment by systematic-meerca** [comment]
Thank you again @nonhic! I'm certainly not active anymore (either here or on Neopets these days), just so happened to check the related e-mail today :)  I'll try to keep an eye on it more often.
